import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { CartProvider } from 'use-shopping-cart';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'E-commerce website',
  description: 'E-commerce website generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={inter.className}>
        <CartProvider
          stripe={process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY!}
          currency="USD"
          shouldPersist
          cartMode="checkout-session"
        >
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
